spring.application.name=coffee-app
server.port=8005

# Dubbo 3.x 配置
dubbo.application.name=coffee-app
dubbo.application.serialize-check-status=WARN
dubbo.registry.address=nacos://localhost:8848
dubbo.protocol.name=dubbo
